language: node_js

cache: npm

node_js:
    - '12'
    - '13'

services:
    - docker

git:
    depth: 3

branches:
    only:
        - master

addons:
    apt:
        packages:
            - docker-ce

env:
    global:
        - NODE_ENV=test
        - PORT=3000
        - JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4
        - JWT_EXPIRATION_MINUTES=15
        - MONGO_URI=mongodb://localhost:27017/ledger-app
        - MONGO_URI_TESTS=mongodb://localhost:27017/ledger-app-tests
        - EMAIL_PORT=587
        - EMAIL_HOST=smtp-relay.sendinblue.com
        - EMAIL_USERNAME=tlang50@icloud.com
        - CI=true

script: npm run docker:test
after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push travla5/ledger
