version: '3.7'
services:
    api:
        image: ledger-server
        command: npm run docker:test
        environment:
            - NODE_ENV=test
            - PORT=3000
            - JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4
            - JWT_EXPIRATION_MINUTES=15
            - MONGO_URI=mongodb://mongodb:27017/ledger-app
            - MONGO_URI_TESTS=mongodb://mongodb:27017/ledger-app-tests
            - EMAIL_PORT=587
            - EMAIL_HOST=smtp-relay.sendinblue.com
            - EMAIL_USERNAME=tlang50@icloud.com
            - EMAIL_PASSWORD
        healthcheck:
            disable: true
