version: '3.7'
services:
    api:
        command: npm run test
        environment:
            - MONGO_URI_TESTS=mongodb://mongodb:27017/ledger-app-tests
        healthcheck:
            disable: true
