version: '3.7'
services:
    api:
        build: .
        command: npm run dev
        container_name: ledger
        environment:
            - MONGO_URI=mongodb://mongodb:27017/ledger-app
            - NODE_ENV=development
            - PORT=3000
            - JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4
            - JWT_EXPIRATION_MINUTES=15
            - MONGO_URI_TESTS=mongodb://mongodb:27017/ledger-app-tests
            - EMAIL_PORT=587
            - EMAIL_HOST=smtp-relay.sendinblue.com
            - EMAIL_USERNAME=tlang50@icloud.com
            - EMAIL_PASSWORD=346234
        volumes:
            - .:/opt/ledger-server/app
            - notused:/opt/ledger-server/app/node_modules
        ports:
            - '3000:3000'
        depends_on:
            - mongodb

    mongodb:
        image: mongo
        ports:
            - '27017:27017'
volumes:
    notused:
